apiVersion: v1
kind: Secret
metadata:
  name: profiler-secret
  namespace: profiler
type: Opaque
stringData:
  DB_USER: "profiler"
  DB_PASSWORD: "profiler"
  POSTGRES_USER: "profiler"
  POSTGRES_PASSWORD: "profiler"
