apiVersion: v1
kind: ServiceAccount
metadata:
  name: vgpu-profiler
  namespace: profiler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vgpu-profiler
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vgpu-profiler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vgpu-profiler
subjects:
  - kind: ServiceAccount
    name: vgpu-profiler
    namespace: profiler
