apiVersion: v1
kind: Service
metadata:
  name: recommender
  namespace: profiler
  labels:
    app: recommender
spec:
  selector:
    app: recommender
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
