apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: profiler
  labels:
    app: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      serviceAccountName: web-ui
      containers:
        - name: web-ui
          image: docker.io/loihoangthanh1411/recommendation-web:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: http
          envFrom:
            - configMapRef:
                name: web-ui-config
          volumeMounts:
            - name: pod-template
              mountPath: /etc/pod-template
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: pod-template
          configMap:
            name: pod-template
      restartPolicy: Always
