apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-ui
  namespace: profiler
---
# Allow web-ui to create / get / delete pods in test-dra namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-ui-pod-manager
  namespace: test-dra
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-ui-pod-manager
  namespace: test-dra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-ui-pod-manager
subjects:
  - kind: ServiceAccount
    name: web-ui
    namespace: profiler
